airflow_db_raw:
  target: dev
  outputs:
    dev:
      type: postgres
      host: postgres
      user: postgres
      password: postgres
      port: 5432
      dbname: postgres
      schema: dbt
      threads: 4

airflow_db:
  target: dev
  outputs:
    dev:
      type: postgres
      host: 192.168.1.110
      user: usr_airflow
      password: airflow7812
      port: 5432
      dbname: airflowdb
      schema: dbt
      threads: 4
